version: "3.8"
services:
  client:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm start

volumes:
  node_modules:
